# Generated by Django 3.1.6 on 2021-02-15 15:16

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import mainApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.TextField()),
                ('oib', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('birth_date', models.DateField()),
                ('best_position', enumchoicefield.fields.EnumChoiceField(default=mainApp.models.Positions(1), enum_class=mainApp.models.Positions, max_length=18)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('club_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.club')),
                ('manager_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.manager')),
            ],
        ),
    ]
