# Generated by Django 3.1.6 on 2021-02-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210217_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_modified']},
        ),
    ]
